[phases.setup]
nixPkgs = ['python311', 'postgresql']
nixLibs = ['python311']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt', 'python -m pip install gunicorn']

[phases.build]
cmds = ['python manage.py migrate']

[start]
cmd = 'gunicorn horilla.wsgi:application --bind 0.0.0.0:8000 --workers 3'
