# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_in_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-In Latitude'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_in_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-In Longitude'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_out_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-Out Latitude'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_out_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-Out Longitude'),
        ),
    ]
